# Install the R app.
---
- stat:
    path: /Applications/R.app
  register: throwaway
  when: not r_app_force_install

- block:
    - name: Download R package
      get_url:
        url: "https://cloud.r-project.org/bin/macosx/base/R-{{ r_version }}.pkg"
        dest: "{{ downloads }}/R.pkg"

    - name: Install R
      command: "installer -pkg {{ downloads }}/R.pkg -target /"
      become: yes

  when: r_app_force_install or not (throwaway.stat.isdir is defined and throwaway.stat.isdir)
