# Download and install MacTeX
---
- stat:
    path: /usr/local/texlive
  register: throwaway

- block:
    - name: Download MacTeX
      get_url:
        url: https://mirror.ctan.org/systems/mac/mactex/MacTeX.pkg
        dest: "{{ downloads }}/mactex.pkg"

    - name: Install MacTeX
      command: "installer -pkg {{ downloads }}/mactex.pkg -target /"
      become: yes
  when: not (throwaway.stat.isdir is defined and throwaway.stat.isdir)
