# Download and install MacTeX
---
- stat:
    path: /usr/local/texlive
  register: throwaway
  when: not mactex_force_install

- when: mactex_force_install or not (throwaway.stat.isdir is defined and throwaway.stat.isdir)
  block:
    - name: Download MacTeX
      get_url:
        url: https://mirror.ctan.org/systems/mac/mactex/MacTeX.pkg
        dest: "{{ downloads }}/mactex.pkg"
        force: "{{ mactex_force_download }}"
        mode: u=rw

    - name: Install MacTeX
      command: "installer -pkg {{ downloads }}/mactex.pkg -target /"
      become: true
