---
- name: Show all file extensions in Finder
  osx_defaults:
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: Disable "Natural" (backwards) scrolling
  osx_defaults:
    key: com.apple.swipescrolldirection
    type: bool
    value: false
