# Download and install Postman.
---
- stat:
    path: "{{ postman_app_path }}/{{ postman_app_name }}.app"
  register: throwaway

- block:
    - name: Install Postman
      unarchive:
        dest: "{{ postman_app_path }}/{{ postman_app_name }}.app"
        src: https://dl.pstmn.io/download/latest/osx
  when: not (throwaway.stat.isdir is defined and throwaway.stat.isdir)
