# Download and install Postman.
---
- stat:
    path: "{{ postman_app_path }}/{{ postman_app_name }}.app"
  register: throwaway

- block:
    - name: Download Postman
      get_url:
        url: "https://dl.pstmn.io/download/latest/osx"
        dest: "{{ downloads }}/postman.zip"
    - name: Unzip Postman
      unarchive:
        dest: "{{ downloads }}"
        src: "{{ downloads }}/postman.zip"
    - name: Install Postman
      command: "mv {{ downloads }}/Postman.app {{ postman_app_path }}"
  when: not (throwaway.stat.isdir is defined and throwaway.stat.isdir)
