# Install xACT
---
- stat:
    path: "{{ xact_app_path }}/{{ xact_app_name }}.app"
  register: throwaway

- block:
    - name: Download xACT
      get_url:
        url:  " http://xact.scottcbrown.org/xACT{{ xact_version }}.zip"
        dest: "{{ downloads }}/xact.zip"
    - name: Unzip xACT
      unarchive:
        dest: "{{ downloads }}"
        src: "{{ downloads }}/xact.zip"
    - name: Install xACT
      command: "mv {{ downloads }}/{{ xact_app_name }}.app {{ xact_app_path }}"
  when: not (throwaway.stat.isdir is defined and throwaway.stat.isdir)
