# Install xACT
---
- stat:
    path: "{{ xact_app_path }}/{{ xact_app_name }}.app"
  register: throwaway
  when: not xact_force_install

- set_fact:
    xact_local_zip: "{{ downloads }}/xact.zip"
    xact_unarchive_dir: "{{ downloads }}/xACT"

- when: xact_force_install or not (throwaway.stat.isdir is defined and throwaway.stat.isdir)
  block:
    - file:
        path: "{{ xact_unarchive_dir }}"
        state: directory
        mode: u=rwx

    - name: Download xACT
      get_url:
        url: "http://xact.scottcbrown.org/xACT{{ xact_version }}.zip"
        dest: "{{ xact_local_zip }}"
        force: "{{ xact_force_download }}"
        mode: u=rw

    - name: Unzip xACT
      unarchive:
        dest: "{{ xact_unarchive_dir }}"
        src: "{{ xact_local_zip }}"

    - name: Install xACT
      command: "mv {{ downloads }}/xACT/xACT{{ xact_version }}/{{ xact_app_name }}.app {{ xact_app_path }}"

  always:
    - file:
        path: "{{ xact_unarchive_dir }}"
        state: absent
