# Add a user to the sudoers database, optionally with the ability to sudo without a password.
#
# Extra vars:
#   user: name of the user to add to the sudoers database. Default is the current user.
#   nopasswd: boolean indicating whether the user has passwordless sudo. Default is false.
#
#  Example -- add passwordless sudo for user Bob
#     ansible-playbook -K sudoers-playbook.yml -e nopasswd=yes -e user=Bob
---
- name: Add sudoers
  hosts: localhost
  become: false
  vars:
    nopasswd: false
    user: "{{ ansible_user_id }}"
  tasks:
    - set_fact:
        sudoers_line: "{{ user }}            ALL = (ALL) NOPASSWD:ALL"
      when: nopasswd | bool

    - set_fact:
        sudoers_line: "{{ user }}            ALL = (ALL) ALL"
      when: not (nopasswd | bool)

    - name: Add new file to /etc/sudoers.d
      template:
        dest: "/etc/sudoers.d/{{ user }}"
        src: "templates/content.j2"
        validate: /usr/sbin/visudo -cf %s
        owner: root
        group: wheel
        mode: ug=r
      become: true
      vars:
        content: "{{ sudoers_line }}"
