# Download and install XQuartz.
---
- stat:
    path: /usr/X11/bin/Xquartz
  register: throwaway

- block:
  - name: Download XQuartz
    get_url:
      url: "https://dl.bintray.com/xquartz/downloads/XQuartz-{{ xquartz_version }}.dmg"
      dest: "{{ downloads }}/xquartz.dmg"

  - block:
    - name: Mount XQuartz disk image
      include_role:
        name: mount_dmg
      vars:
        path: "{{ downloads }}/xquartz.dmg"
        mountpoint: xquartz

    - name: Install XQuartz
      command: "installer -pkg /Volumes/xquartz/XQuartz.pkg -target /"

    become: yes
    always:
      - name: Unmount XQuartz disk image
        include_role:
          name: unmount_dmg
        vars:
          mountpoint: xquartz

  when: not throwaway.stat.executable