# Download and install MacPorts
#  https://www.macports.org/
---
- stat:
    path: /opt/local/bin/port
  register: macports_stat
  when: not macports_force_install

- when: macports_force_install or not (macports_stat.stat.executable is defined and macports_stat.stat.executable)
  block:
    # MacPorts for older OS versions uses the major.minor versioning scheme.
    - set_fact:
        macports_macos_version: "{{ macos_version_info.major_minor }}"
      when: macos_version_info.major == "10"

    # Starting with Big Sur, macOS major version numbers get bumped, and MacPorts package files are named with only the
    # major version.
    - set_fact:
        macports_macos_version: "{{ macos_version_info.major }}"
      when: macos_version_info.major != "10"

    - set_fact:
        # Marketing version has no spaces in package name, e.g., Big Sur -> BigSur.
        macports_marketing_version: "{{ macos_version_info.marketing | regex_replace('\\s', '') }}"

    - set_fact:
        macports_macos_package_name:
          "MacPorts-{{ macports_version }}-{{ macports_macos_version }}-{{ macports_marketing_version }}.pkg"

    - name: Download MacPorts
      get_url:
        url: "https://distfiles.macports.org/MacPorts/{{ macports_macos_package_name }}"
        dest: "{{ downloads }}/macports.pkg"
        force: "{{ macports_force_download }}"
        mode: u=rw

    - name: Install MacPorts
      command: "installer -pkg {{ downloads }}/macports.pkg -target /"
      become: true

    - name: Add MacPorts (bin) to path
      lineinfile:
        line: /opt/local/bin
        path: /etc/paths
        state: present
        insertbefore: /usr/local/bin
      become: true

    - name: Add MacPorts (sbin) to path
      lineinfile:
        line: /opt/local/sbin
        path: /etc/paths
        state: present
        insertbefore: /usr/local/bin
      become: true
