# Install MusicBrainz Picard
#  https://picard.musicbrainz.org/
---
- name: Download and install MusicBrainz Picard
  include_role:
    name: install_from_dmg
  vars:
    install_from_dmg_app_name: "MusicBrainz Picard"
    install_from_dmg_image_url: "https://data.musicbrainz.org/pub/musicbrainz/picard/MusicBrainz-Picard-{{ picard_version }}-macOS-10.14.dmg"
    install_from_dmg_image_destination: "{{ downloads }}/picard.dmg"
    install_from_dmg_force_download: "{{ picard_force_download }}"
    install_from_dmg_force_install: "{{ picard_force_install }}"
