# Customize macOS and app settings.
---
- include_role:
    name: defaults
    apply:
      tags:
        - customize
  tags:
    - customize

- name: Show ~/Library
  command: chflags nohidden "{{ '~/Library' | expanduser }}"
  tags:
    - customize

- name: No, really, show ~/Library
  command: SetFile -a v "{{ '~/Library' | expanduser }}"
  tags:
    - customize
