---
# Install separately, since some ports require it, or at least look for it, causing prompts.
- name: Install OpenJDK
  macports:
    selfupdate: yes
    upgrade: yes
    name: openjdk8
    state: present
  become: yes

- name: Install ports
  macports:
    selfupdate: yes
    upgrade: yes
    name: "{{ item.key }}"
    variant: "{{ item.value }}"
    state: present
  become: yes
  with_dict: "{{ ports_to_install }}"

- name: Select port
  command: "port select {{ item.key }} {{ item.value }}"
  become: yes
  with_dict: "{{ ports_to_select }}"
