---
# selfupdate here, once, so that we don't stupidly do it for every port we install...
- name: Run port selfupdate
  macports:
    selfupdate: yes
  become: yes

# TODO force deactivation of poppler on condition that it's about to be upgraded.
# check port list outdated output after selfupdate but before upgrade.

- name: Upgrade installed ports
  macports:
    upgrade: yes
  become: yes

# Install separately, since some ports require it, or at least look for it, causing prompts.
- name: Install OpenJDK
  macports:
    name: openjdk8
    state: present
  become: yes

- name: Install ports
  macports:
    name: "{{ item.key }}"
    variant: "{{ item.value }}"
    state: present
  become: yes
  with_dict: "{{ ports_to_install }}"

- name: Select port
  command: "/opt/local/bin/port select {{ item.key }} {{ item.value }}"
  become: yes
  with_dict: "{{ ports_to_select }}"

- name: Reclaim space
  command: /opt/local/bin/port reclaim --disable-reminders
  become: yes
