---
- name: Load launchd jobs
  include_role:
    name: launchd_load
  vars:
    launchd_label: "{{ item.label }}"
    launchd_plist: "{{ item.plist }}"
    launchd_load_become: "{{ item.become | default(True) }}"
  with_items: "{{ launchd_jobs }}"
