---
- name: Install global Python packages
  pip:
    executable: pip3
    name: "{{ pip_global_packages_to_install }}"
    state: present
    extra_args: --upgrade
  become: true

- name: Install user Python packages
  pip:
    executable: pip3
    name: "{{ pip_user_packages_to_install }}"
    state: present
    extra_args: --user --upgrade
