# Set up ssh keys, known_hosts, etc.
#
# Allows use of git@github.com in git tasks, etc.
---
- set_fact:
    ssh_config_dir: "{{ '~/.ssh' | expanduser }}"

- set_fact:
    ssh_known_hosts_file: "{{ ssh_config_dir }}/known_hosts"

- name: Ensure ~/.ssh exists
  file:
    path: "{{ ssh_config_dir }}"
    state: directory
    mode: u=rwx

- name: Ensure known_hosts exists
  file:
    path: "{{ ssh_known_hosts_file }}"
    state: touch
    mode: u=rw

- name: Check for github in known_hosts
  command: "grep '^github\\.com' {{ ssh_known_hosts_file }}"
  register: throwaway
  changed_when: false  # Does not change anything. Checks status.
  ignore_errors: true

- when: throwaway.rc != 0
  block:
    - name: Get github ssh host key
      command: "ssh-keyscan -t ecdsa github.com"
      changed_when: false  # Does not change anything. Just loads data into a variable.
      register: github_ssh_keyscan

    # does not work with default ansible_shell_executable (/bin/sh), an absolutely ancient version of bash.
    # for this reason, we're using zsh (see the inventory file).
    - name: Get github ssh host key fingerprint
      shell: "ssh-keygen -lf - <<< '{{ github_ssh_keyscan.stdout }}'"
      changed_when: false  # Does not change anything. Just loads data into a variable.
      register: github_ssh_fingerprint

    # Compare fingerprint to https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
    - name: Fail if github ssh host key fingerprint doesn't match published value
      fail:
        msg: ssh key mismatch
      when: github_ssh_fingerprint.stdout != '256 SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM github.com (ECDSA)'

    - name: Add github ssh host key to known_hosts
      lineinfile:
        path: "{{ ssh_known_hosts_file }}"
        line: "{{ github_ssh_keyscan.stdout }}"

# TODO ssh keys from secrets
