# Download and install ngrok
#
# Set ngrok_force_install to reinstall.
---
- stat:
    path: /usr/local/bin/ngrok
  register: throwaway
  when: not ngrok_force_install


- when: ngrok_force_install or not (throwaway.stat.executable is defined and throwaway.stat.executable)
  block:
    - set_fact:
        ngrok_zip_arch: "{{ 'amd64' if (ansible_machine == 'x86_64') else ansible_machine }}"

    - name: Download ngrok
      get_url:
        url: "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-{{ ngrok_zip_arch }}.zip"
        dest: "{{ downloads }}/ngrok.zip"
        force: "{{ ngrok_force_download }}"
        mode: u=rw

    - name: Unzip ngrok
      unarchive:
        dest: "{{ downloads }}"
        src: "{{ downloads }}/ngrok.zip"

    - name: Install ngrok
      command: "mv {{ downloads }}/ngrok /usr/local/bin"
      become: true
