# Download and install ngrok
---
- stat:
    path: /usr/local/bin/ngrok
  register: throwaway

- block:
  - name: Download ngrok
    get_url:
      url: "https://bin.equinox.io/c/{{ ngrok_hash }}/ngrok-stable-darwin-amd64.zip"
      dest: "{{ downloads }}/ngrok.zip"
  - name: Unzip ngrok
    unarchive:
      dest: "{{ downloads }}"
      src: "{{ downloads }}/ngrok.zip"
  - name: Install ngrok
    command: "mv {{ downloads }}/ngrok /usr/local/bin"
    become: yes
  when: not(throwaway.stat.executable is defined and throwaway.stat.executable)
