---
iterm2_shell_integration_force_install: false
# Utilities to install.
# See https://github.com/gnachman/iTerm2-shell-integration/blob/main/shell_integration/install_shell_integration_and_utilities.sh
iterm2_shell_integration_utilities:
  - imgcat
  - imgls
  - it2api
  - it2attention
  - it2check
  - it2copy
  - it2dl
  - it2getvar
  - it2git
  - it2setcolor
  - it2setkeylabel
  - it2tip
  - it2ul
  - it2universion
  - it2profile
  - it2cat
