# Load a launchd plist if it's not already loaded.
---
- name: Check for job
  command: "launchctl list {{ launchd_label }}"
  become: "{{ launchd_load_become | default(True) }}"
  register: throwaway
  ignore_errors: true

- name: Load job
  command: "launchctl load -w {{ launchd_plist }}"
  become: "{{ launchd_load_become | default(True) }}"
  when: throwaway.rc != 0
