# Install GNU parallel using MacPorts, and disable its nagging.
---
- name: Install parallel
  macports:
    name: parallel
    state: present
  become: true

- set_fact:
    throwaway: "{{ '~/.parallel' | expanduser }}"

- name: Ensure configuration directory exists
  file:
    path: "{{ throwaway }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

  # I'm never publishing a paper...
- name: Silence citation warning
  file:
    path: "{{ throwaway }}/will-cite"
    state: touch
    mode: u=rw,g=r,o=r
