---
- set_fact:
    emacs_src_dir: "{{ '~/src/emacs' | expanduser }}"
    emacs_log_file: "{{ '~/var/log/emacs.log' | expanduser }}"
    # TODO This might vary between runs. Could be a problem.
    emacs_daemon_path: "{{ lookup('env', 'PATH') }}"

- name: Clone emacs
  git:
    repo: https://github.com/emacs-mirror/emacs
    dest: "{{ emacs_src_dir }}"
    force: yes # discard build-aux/config.{sub,guess}

- name: Run make distclean
  command: /opt/local/bin/gmake distclean
  args:
    chdir: "{{ emacs_src_dir }}"
  when: emacs_distclean

# make bootstrap is sometimes necessary. See INSTALL.REPO and
# https://lists.gnu.org/archive/html/emacs-devel/2019-11/msg00630.html
- name: Bootstrap emacs
  command: /opt/local/bin/gmake bootstrap
  args:
    chdir: "{{ emacs_src_dir }}"
  when: emacs_bootstrap

- name: Generate configure script
  command: ./autogen.sh
  args:
    chdir: "{{ emacs_src_dir }}"
  when: not emacs_bootstrap  # bootstrap runs autogen.

# Standalone step can fail with "New Mach-O header is too large to relocate" without LDFLAGS.
# https://py2app.readthedocs.io/en/latest/faq.html
# Vaguely related: https://ylluminarious.github.io/2019/06/13/how-i-solved-a-cryptic-emacs-dumping-error/
# Interestingly, configure will fail if LDFLAGS is set via LDFLAGS=... ./configure, or if it's done via
# `environment:` on ansible's command module.
- name: Configure emacs
  shell: |-
    export LDFLAGS=-Wl,-headerpad_max_install_names
    ./configure
  args:
    chdir: "{{ emacs_src_dir }}"

- name: Build emacs
  command: /opt/local/bin/gmake install
  args:
    chdir: "{{ emacs_src_dir }}"

- name: Create app's Frameworks directory (for standalone app libraries)
  file:
    path: "{{ emacs_src_dir }}/nextstep/Emacs.app/Contents/Frameworks"
    state: directory

# From a handy tip here
# https://www.reddit.com/r/emacs/comments/bclyyc/building_emacs_from_source_on_macos/
- name: Make emacs standalone
  command: /usr/bin/python3 -m macholib standalone nextstep/Emacs.app
  args:
    chdir: "{{ emacs_src_dir }}"

#- set_fact:
#    emacs_launchd_plist: "{{ '~/Library/LaunchAgents' | expanduser }}/org.gnu.emacs.daemon.plist"

# https://www.emacswiki.org/emacs/EmacsAsDaemon#toc8
#- name: Create launchd service for emacs server
#  template:
#    src: emacs.plist.j2
#    dest: "{{ emacs_launchd_plist }}"

#- name: Unload emacs server launchd service
#  include_role:
#    name: launchd_unload
#  vars:
#    launchd_label: org.gnu.emacs.daemon
#    launchd_plist: "{{ emacs_launchd_plist }}"
#    launchd_become: no

- name: Copy emacs to /Applications
  command: cp -af nextstep/Emacs.app /Applications/
  args:
    chdir: "{{ emacs_src_dir }}"

#- name: Load emacs server launchd service
#  include_role:
#    name: launchd_load
#  vars:
#    launchd_label: org.gnu.emacs.daemon
#    launchd_plist: "{{ emacs_launchd_plist }}"
#    launchd_become: no
