---
- set_fact:
    emacs_src_dir: "{{ '~/src/emacs' | expanduser }}"

- name: Clone emacs
  git:
    repo: https://github.com/emacs-mirror/emacs
    dest: "{{ emacs_src_dir }}"

# Standalone step can fail with "New Mach-O header is too large to relocate" without LDFLAGS.
# https://py2app.readthedocs.io/en/latest/faq.html
# Vaguely related: https://ylluminarious.github.io/2019/06/13/how-i-solved-a-cryptic-emacs-dumping-error/
# Interestingly, configure will fail if LDFLAGS is set via LDFLAGS=... ./configure, or if it's done via
# `environment:` on ansible's command module.
- name: Configure emacs
  shell: |-
    export LDFLAGS=-Wl,-headerpad_max_install_names
    ./configure
  args:
    chdir: "{{ emacs_src_dir }}"

- name: Build emacs
  command: /opt/local/bin/gmake install
  args:
    chdir: "{{  emacs_src_dir }}"

- file:
    path: "{{ emacs_src_dir }}/nextstep/Emacs.app/Contents/Frameworks"
    state: directory

# From a handy tip here
# https://www.reddit.com/r/emacs/comments/bclyyc/building_emacs_from_source_on_macos/
- name: Make emacs standalone
  command: /usr/bin/python3 -m macholib standalone nextstep/Emacs.app
  args:
    chdir: "{{  emacs_src_dir }}"

# https://www.emacswiki.org/emacs/EmacsAsDaemon#toc8
- name: Create launchd service for emacs server
  copy:
    src: emacs.plist
    dest: "{{ '~/Library/LaunchAgents' | expanduser }}/org.gnu.emacs.daemon.plist"

- name: Copy emacs to /Applications
  command: cp -af nextstep/Emacs.app /Applications/
  args:
    chdir: "{{ emacs_src_dir }}"
