# Install steamcmd (the command line interface to the steam console)
# https://developer.valvesoftware.com/wiki/SteamCMD#macOS
---
- set_fact:
    steamcmd_script: "{{ steamcmd_dest_dir }}/steamcmd.sh"

- stat:
    path: "{{ steamcmd_script }}"
  register: throwaway
  when: not steamcmd_force_install

- when: steamcmd_force_install or not throwaway.stat.exists
  block:
    - name: Download steamcmd
      get_url:
        url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_osx.tar.gz
        dest: "{{ downloads }}/steamcmd.tar.gz"
        force: "{{ steamcmd_force_download }}"
        mode: u=rw

    - name: Create steamcmd directory
      file:
        path: "{{ steamcmd_dest_dir }}"
        state: directory
        mode: u=rwx

    - name: Install steamcmd
      unarchive:
        src: "{{ downloads }}/steamcmd.tar.gz"
        dest: "{{ steamcmd_dest_dir }}"

    - name: Update steamcmd
      command: "{{ steamcmd_script }} +quit"
