# Install VirtualBox and the extension pack.
---
- stat:
    path: "/Applications/VirtualBox.app"
  register: throwaway

- block:
    - name: Download VirtualBox
      get_url:
        url: "https://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/VirtualBox-{{ virtualbox_version }}-{{ virtualbox_revision }}-OSX.dmg"
        dest: "{{ downloads }}/VirtualBox.dmg"
        checksum: "sha256:https://www.virtualbox.org/download/hashes/{{ virtualbox_version }}/SHA256SUMS"

    - include_role:
        name: mount_dmg
      vars:
        path: "{{ downloads }}/VirtualBox.dmg"
        mountpoint: "VirtualBox"

    - name: Install VirtualBox
      command: "installer -pkg /Volumes/VirtualBox/VirtualBox.pkg -target /"
      become: yes

  always:
    - include_role:
        name: unmount_dmg
      vars:
        mountpoint: "VirtualBox"
  when: not (throwaway.stat.isdir is defined and throwaway.stat.isdir)

- name: Check for VirtualBox extensions
  command: VBoxManage list extpacks
  register: throwaway

- block:
    - set_fact:
        vbox_extpack_file: "{{ downloads }}/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack"

    - name: Download VirtualBox extensions
      get_url:
        url: "https://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack"
        dest: "{{ vbox_extpack_file }}"
        checksum: "sha256:https://www.virtualbox.org/download/hashes/{{ virtualbox_version }}/SHA256SUMS"

    - block:
        - name: Create temporary directory
          command: mktemp -d
          register: tempdir

        - name: Extract VirtualBox extensions license file
          unarchive:
            src: "{{ vbox_extpack_file }}"
            dest: "{{ tempdir.stdout }}"

        - name: Compute VirtualBox extensions license hash
          shell: "/usr/bin/shasum -a 256 {{ tempdir.stdout }}/ExtPack-license.txt | cut -d ' ' -f 1"
          register: vbox_license_sha256

      always:
        - name: Delete temporary directory
          file:
            path: "{{ tempdir.stdout }}"
            state: absent

    - name: Install VirtualBox extensions
      command: "VBoxManage extpack install --replace {{ vbox_extpack_file }} --accept-license={{ vbox_license_sha256.stdout }}"
      become: yes

  when: not throwaway.stdout is search("Oracle VM VirtualBox Extension Pack")
