# Install terraform
#
# Set terraform_force_install to true to reinstall.
---
- stat:
    path: "/usr/local/bin/terraform"
  register: throwaway
  when: not terraform_force_install

- when: terraform_force_install or not throwaway.stat.exists
  block:
    - name: Download terraform
      get_url:
        url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_darwin_amd64.zip"
        dest: "{{ downloads }}/terraform.zip"
        checksum: "sha256:https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_SHA256SUMS"
        force: "{{ terraform_force_download }}"
        mode: u=rw

    - name: Install terraform
      unarchive:
        src: "{{ downloads }}/terraform.zip"
        dest: "/usr/local/bin"
      become: true
