---
argument_specs:
  main:
    short_description: Install node using nvm.
    description: >-
      Downloads and installs nvm and uses it to install a specific node version.
    options:
      node_global_modules_to_install:
        description: >-
          A dict of with required `name` and optional `version` keys. The `name` is the name of the npm module to
          install. The `version` is the specific version.
          
          If `version` is omitted, the default is the special string `latest`, which will install the latest version.
          
          For example, the following would install the latest version of `foo` and `bar, and would install version
          `1.0.0` of `quux`: 
          
          ```
            node_global_modules_to_install: 
              - name: foo
              - name: bar
                version: "latest"
              - name: quux
                version: "1.0.0"
          ```
        type: dict
        default: {}
      node_npm_version:
        description: >-
          The version of npm to install.

          The special string `latest` will install the latest version.
          
          If omitted (i.e., None), no version is installed (i.e., the version that comes with node will be used). This
          is the default behavior.
        type: str
        # Default is None, but this makes validation explode.
      node_version:
        description: >-
          The node version to install. Must be supported by nvm.
          
          Do not include the leading `v`. E.g., to install node version v20.0.0, pass "20.0.0".
        type: str
        required: true
      node_nvm_home:
        description: >-
          The directory into which nvm should be cloned.
          
          If not provided, this defers to the `nvm` role's defaults.
        type: str
        required: false
