# Install node via nvm.
#  https://github.com/nvm-sh/nvm
#
# This installs nvm by cloning its GitHub repository. It then uses nvm to install the requested node version.
---
- set_fact:
    node_version_string: "{{ 'v' + node_version }}"
    node_source_nvm: "source {{ nvm_home }}/nvm.sh"
- set_fact:
    node_version_root: "{{ node_nvm_home + '/versions/node/' + node_version_string }}"

- name: Install node.js
  shell: "{{ node_source_nvm }} && nvm install {{ node_version_string }}"
  args:
    creates: "{{ node_version_root }}"

- name: Install npm
  shell: "{{ node_source_nvm }} && nvm use '{{ node_version_string }}' && npm install -g npm@{{ node_npm_version }}"
  when: node_npm_version != None

- name: Install global modules
  community.general.npm:
    name: "{{ item.key }}"
    version: "{{ item.value | default(latest) }}"
    global: true
  loop: "{{ node_global_modules_to_install | dict2items }}"
  environment:
    PATH: "{{ lookup('ansible.builtin.env', 'PATH') }}:{{ node_version_root }}/bin"
