# Install node via nvm.
---
- set_fact:
    node_nvm_home: "{{ '~/.nvm' | expanduser }}"
    node_version_string: "{{ 'v' + node_version }}"
    node_source_nvm: "source {{ '~/.nvm/nvm.sh' | expanduser }}"

- name: Clone nvm
  git:
    repo: https://github.com/nvm-sh/nvm
    dest: "{{ node_nvm_home }}"

- name: Install node.js
  shell: "{{ node_source_nvm }} && nvm install {{ node_version_string }}"
  args:
    creates: "{{ node_nvm_home + '/versions/node/' + node_version_string }}"

- name: Use correct node.js version
  shell: "{{ node_source_nvm }} && nvm alias default {{ node_version_string }}"

- name: Install npm
  shell: "{{ node_source_nvm }} && nvm use default && npm install -g npm@{{ node_npm_version }}"
  when: node_npm_version != None

- name: Install yarn
  shell: "{{ node_source_nvm }} && nvm use default && npm install -g yarn@{{ node_yarn_version }}"
  when: node_yarn_version != None
