---
argument_specs:
  main:
    short_description: Install GPG Tools.
    description: >-
      Installs GPG Tools.
    options:
      gpg_tools_force_download:
        description: >-
          If True, download GPG Tools, even if it's already been downloaded.
        type: bool
        default: false
      gpg_tools_force_install:
        description: >-
          If True, install GPG Tools, even if it's already been installed.
        type: bool
        default: false
      gpg_tools_version:
        description: >-
          The version of GPG Tools to install.
        type: "str"
