# Install 1password.
# https://downloads.1password.com/mac/1Password.zip
---
- set_fact:
    one_password_app: "/Applications/1Password.app"

- stat:
    path: "{{ one_password_app }}"
  register: throwaway
  when: not one_password_force_install

- when: one_password_force_install or not(throwaway.stat.isdir is defined and throwaway.stat.isdir)
  block:
    - set_fact:
        one_password_local_zip: "{{ downloads }}/1password.zip"
        one_password_unarchive_dir: "{{ downloads }}/1password"
    - file:
        path: "{{ one_password_unarchive_dir }}"
        state: directory
        mode: u=rwx
    - name: Download 1password
      get_url:
        url: "https://downloads.1password.com/mac/1Password.zip"
        dest: "{{ one_password_local_zip }}"
        force: "{{ one_password_force_download }}"
        mode: u=rw
    - name: Unzip 1password
      unarchive:
        dest: "{{ one_password_unarchive_dir }}"
        src: "{{ one_password_local_zip }}"
    - name: Install 1password
      command: "open -a '{{ one_password_unarchive_dir }}/1Password Installer.app'"
      creates: "{{ one_password_app }}"

  always:
    - file:
        path: "{{ one_password_unarchive_dir }}"
        state: absent
