# Install ProtonVPN.
#  https://protonvpn.com/
---
- set_fact:
    proton_vpn_dmg_url: "https://vpn.protondownload.com/download/macos/{{ proton_vpn_version }}/ProtonVPN_mac_v{{ proton_vpn_version }}.dmg"

- name: Download and install ProtonVPN
  include_role:
    name: install_from_dmg
  vars:
    install_from_dmg_app_name: "ProtonVPN"
    install_from_dmg_image_url: "{{ proton_vpn_dmg_url }}"
    install_from_dmg_image_destination: "{{ downloads }}/ProtonVPN.dmg"
    install_from_dmg_force_download: "{{ proton_vpn_force_download }}"
    install_from_dmg_force_install: "{{ proton_vpn_force_install }}"
