---
argument_specs:
  main:
    short_description: Install iTerm2.
    description: >-
      Downloads and installs iTerm2.
    options:
      iterm2_app_name:
        description: >-
          Name of the iTerm2 application
        type: str
        default: iTerm2
      iterm2_app_path:
        description: >-
          Directory where the iTerm2 application should be installed. For example, `/Applications` or 
          `{{ '~/Applications' | expanduser }}` would be reasonable choices.
        type: path
        default: /Applications
      iterm2_force_download:
        description: >-
          If True, download iTerm2, even if it's already been downloaded.
        type: bool
        default: false
      iterm2_force_install:
        description: >-
          If True, install iTerm2, even if it's already installed.
        default: false
      iterm2_version:
        description: >-
          The version of iTerm2 to install.
        type: str
        # Default changes often. See defaults.
