# Install Docker Desktop
---
- set_fact:
    docker_dmg_arch: "{{ 'amd64' if (ansible_machine == 'x86_64') else ansible_machine }}"

- name: Download and install Docker
  include_role:
    name: install_from_dmg
  vars:
    install_from_dmg_app_name: "Docker"
    install_from_dmg_image_url: "https://desktop.docker.com/mac/main/{{ docker_dmg_arch }}/Docker.dmg"
    install_from_dmg_image_destination: "{{ downloads }}/Docker.dmg"
    install_from_dmg_force_download: "{{ docker_force_download }}"
    install_from_dmg_install: "{{ docker_force_install }}"
