---
iterm2_browser_plugin_version: "1.0"
iterm2_browser_plugin_app_path: /Applications
iterm2_browser_plugin_app_name: iTermBrowserPlugin
iterm2_browser_plugin_force_download: false
iterm2_browser_plugin_force_install: false
